@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.yukikazescarlet.decorationmod.machine;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;