@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.yukikaze.decorationmod.machine;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;